### ISSUE TITLE
"The IPE extension requires Jupyter to be installed. Install now?" when using a virtualenv

### ISSUE THREAD

**Issue by pzelnip** [lorenzo2897/vscode-ipe#172] opened 2018-10-25 01:19 UTC
I've created a virtualenvironment and using venvwrapper and installed jupyter into it via pip.  I've picked that environment as my interpreter to use in VS Code, but whenever I execute the "IPE: Open output pane" command, I get: "The IPE extension requires Jupyter to be installed. Install now?"

As an advanced user I'd like to control how Jupyter gets installed and where, as I'm assuming that clicking the "yes install now" on the dialog will install to my system Python rather than my venv Python.

How can I use the extension with the Jupyter installed in my venv?

**Comment by pavanagrawal123** [comment] 2018-10-25 03:26
Hey there! I've fixed this in a fork: https://github.com/pavanagrawal123/VSNotebooks/pull/10

Please try it out and let me know if it works. 

P.S. I left a question for you in one of the issues...

**Comment by LukeyQ1** [comment] 2018-10-25 10:54
This is a duplicate of issue #161 and #162. This issue will be addressed as soon as the repo ownership has been transferred to @neuron-team

**Closed as completed by LukeyQ1** 2018-10-25 10:54 UTC
